/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zzzprojecte;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class MainCRUD extends javax.swing.JFrame {

    ArrayList<Jugador> al = new ArrayList<Jugador>();
    String fitxer = "/home/cristian/NetBeansProjects/fitxerjava.txt";

    /**
     * Creates new form MainCRUD
     */
    public MainCRUD() throws IOException, ClassNotFoundException {
        initComponents();
        meuinitComponents();
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);

        //tableJugador.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLlistar = new javax.swing.JButton();
        btnCrud = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEquip = new javax.swing.JTextField();
        txtPosicio = new javax.swing.JTextField();
        txtFuncio = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJugador = new javax.swing.JTable();

        jLabel5.setText("jLabel5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 16, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 198));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnLlistar.setText("LLISTAR");
        btnLlistar.setMaximumSize(new java.awt.Dimension(100, 100));
        btnLlistar.setMinimumSize(new java.awt.Dimension(100, 100));
        btnLlistar.setPreferredSize(new java.awt.Dimension(100, 100));
        btnLlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLlistar, java.awt.BorderLayout.CENTER);

        btnCrud.setText("CRUD");
        btnCrud.setMaximumSize(new java.awt.Dimension(100, 100));
        btnCrud.setMinimumSize(new java.awt.Dimension(100, 100));
        btnCrud.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrud, java.awt.BorderLayout.PAGE_START);

        jButton3.setText("EXIT");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(198, 198, 198));

        jPanel4.setBackground(new java.awt.Color(221, 221, 221));
        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(60, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 0));

        jLabel1.setText("Posicio");

        jLabel2.setText("Equip");

        jLabel3.setText("Funcio");

        jLabel4.setText("Numero");

        txtEquip.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEquipFocusLost(evt);
            }
        });
        txtEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipActionPerformed(evt);
            }
        });

        txtPosicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPosicioFocusLost(evt);
            }
        });
        txtPosicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPosicioActionPerformed(evt);
            }
        });

        txtFuncio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFuncioFocusLost(evt);
            }
        });
        txtFuncio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncioActionPerformed(evt);
            }
        });

        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFuncio)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPosicio, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtEquip))
                        .addGap(78, 78, 78)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar)
                    .addComponent(btnGuardar))
                .addGap(54, 54, 54))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPosicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar))
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        tableJugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posicio", "Equip", "Funcio", "Numero"
            }
        ));
        tableJugador.setRowHeight(30);
        jScrollPane2.setViewportView(tableJugador);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meuinitComponents() throws IOException, ClassNotFoundException {

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableJugador.getModel();
        tableJugador.setModel(model);

        File f = new File("arxiu.dat");    //Si no s'especifica cap directori s'usa el del projecte
        //Si el fitxer ja existeix copiem el seu contingut al vector agenda. 
        if (f.exists()) {
            ObjectInputStream entrada = new ObjectInputStream(new BufferedInputStream(new FileInputStream(f)));

            while (true) {
                try {
                    Jugador c = (Jugador) entrada.readObject();
                    al.add(c);

                } catch (IOException ex) {
                    break;
                }
            }

        }

    }

    private void btnCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudActionPerformed
        jPanel4.setVisible(true);

    }//GEN-LAST:event_btnCrudActionPerformed

    private void btnLlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarActionPerformed

        jPanel5.setVisible(true);

    }//GEN-LAST:event_btnLlistarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        Jugador jugador = new Jugador(Integer.parseInt(txtPosicio.getText()), txtEquip.getText(), txtFuncio.getText(), Integer.parseInt(txtNumero.getText()));
        al.add(jugador);

        mostrar();

        txtPosicio.setText("");
        txtEquip.setText("");
        txtFuncio.setText("");
        txtNumero.setText("");

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed


    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtFuncioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuncioActionPerformed

    private void txtPosicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosicioActionPerformed

    private void txtEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipActionPerformed

    private void txtPosicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPosicioFocusLost

        if (!(txtEquip.getText().trim().equals(""))) {
            try {
                Integer.parseInt(txtEquip.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ERROR : El Valor ha de ser un número enter major que 0     " + e.getMessage());
            }
        }


    }//GEN-LAST:event_txtPosicioFocusLost

    private void txtEquipFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEquipFocusLost


    }//GEN-LAST:event_txtEquipFocusLost

    private void txtFuncioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFuncioFocusLost


    }//GEN-LAST:event_txtFuncioFocusLost

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost

        if (!(txtNumero.getText().trim().equals(""))) {
            try {
                Integer.parseInt(txtNumero.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ERROR : El Valor ha de ser un número enter major que 0     " + e.getMessage());
            }
        }


    }//GEN-LAST:event_txtNumeroFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        grabarLista(al);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void mostrar() {
        javax.swing.table.DefaultTableModel model1 = (javax.swing.table.DefaultTableModel) tableJugador.getModel();
        // new javax.swing.table.DefaultTableModel(
        // new String[]{"Posicio", "Equip", "Funcio", "Numero"}, 0);
        model1.setRowCount(0);

        for (int i = 0; i < al.size(); i++) {

            model1.addRow(new Object[]{al.get(i).getPosicio(), al.get(i).getEquip(), al.get(i).getFuncio(), al.get(i).getNumero()});

        }

    }

    public boolean grabarLista(ArrayList lista) {
        boolean respuesta = false;
        String mensaje = "";
        String archivo = "/home/cristian/NetBeansProjects/fitxerjava.txt";
        if (!lista.isEmpty()) {
            try {
                ObjectOutputStream ficheroSalida = new ObjectOutputStream(new FileOutputStream(new File(archivo)));

                for (int i = 0; i < al.size(); i++) {
                    ficheroSalida.writeObject(lista);
                    ficheroSalida.flush();
                }

                ficheroSalida.close();
                mensaje = "tDatos de personas guardados correctamente en " + archivo + ".";
                System.out.println("tDatos de personas guardados correctamente en " + archivo + ".");
                respuesta = true;
            } catch (FileNotFoundException fnfe) {
                mensaje = "tError al grabar personas: El fichero " + archivo + " no existe. ";
                System.out.println("tError: El fichero " + archivo + " no existe. ");
                respuesta = false;
            } catch (IOException ioe) {
                mensaje = "tError: Falló la escritura de las personas en el fichero" + archivo + ". ";
                System.out.println("tError: Falló la escritura en el fichero" + archivo + ". ");
                respuesta = false;
            }
        } else {
            mensaje = "tNo hay datos de personas que guardar. La lista está vacía.";
            System.out.println("tNo hay datos que guardar. La lista está vacía. ");
            respuesta = false;
        }
        return respuesta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new MainCRUD().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainCRUD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrud;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLlistar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableJugador;
    private javax.swing.JTextField txtEquip;
    private javax.swing.JTextField txtFuncio;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPosicio;
    // End of variables declaration//GEN-END:variables
}
